language: node_js
node_js:
  - "7.2"
script:
  - echo "Deploying..."
# install:
#   - npm install -g firebase-tools
after_success:
  - firebase login
  - firebase use fmjs-2ef79
  - firebase deploy --token $FIREBASE_TOKEN
